#name of the application (this name must match with the properties file created in the local repository)
spring.application.name=limits-service

spring.config.import=optional:configserver:http://localhost:8888

#configure profile
spring.profiles.active=dev

spring.cloud.config.profile=dev

#custom properties
limits-service.minimum=3
limits-service.maximum=997